### ISSUE TITLE
typo in p calc on heat flux equation

### ISSUE THREAD

**Issue by vrx-** [dpath2o/AFIM#2]
Hey, totally out of the blue: I was looking for a heat flux calc implementation and ran on yours. Not exactly what I need, but I caught a typo in your p eq [here](https://github.com/dpath2o/AFIM/blame/3cbdd445239982406d7d1785f5b9cb1089374be7/src/python/sandbox/regrid_standalone_forcing_cice6.py~#L84C9-L84C9)
should be `C1     = 5.92e-3 + latrad**2*5.25e-3` (no parenthesis).
I know this is sandbox, and I was lazy to do a pr, and your clean code has it corrected elsewhere, but for some reason, my quick search brought me to that file first, so this is in case you wanna do a quick fix. Otherwise, disregard! V.

**Comment by dpath2o** [comment]
thank you, issue resolved
