### ISSUE TITLE
CICE6 standalone initial conditions

### ISSUE THREAD

**Issue by dpath2o** [dpath2o/AFIM#4]
Need to modify https://github.com/dpath2o/AFIM/blob/main/src/python/cice_prep.ipynb to put "pfmice_i" (from o2i.nc, see below) into "frzmlt" initial initial condition (see below).

```
[da1339@gadi-login-08 python]$ ncks -m /g/data/cj50/access-om2/raw-output/access-om2-025/025deg_jra55v13_ryf9091_gmredi6/output052/ocean/o2i.nc
netcdf o2i {
  dimensions:
    nx = 1440 ;
    ny = 1080 ;
    time = UNLIMITED ; // (1 currently)

  variables:
    double pfmice_i(time,ny,nx) ;

    double sslx_i(time,ny,nx) ;

    double ssly_i(time,ny,nx) ;

    double sss_i(time,ny,nx) ;

    double sst_i(time,ny,nx) ;

    double ssu_i(time,ny,nx) ;

    double ssv_i(time,ny,nx) ;

    float time(time) ;
      time:units = "seconds since 0000-00-00 00:00:00" ;
} // group /
```

**Comment by dpath2o** [comment]
Here is "sst_i" field output from:
`/g/data/cj50/access-om2/raw-output/access-om2-025/025deg_jra55v13_ryf9091_gmredi6/output052/ocean/o2i.nc`
![2004-12_sst_i_ACCESS-OM2-025_I2O_SH](https://github.com/dpath2o/AFIM/assets/1684347/8363dfe2-f37b-4321-902e-cf8dd07b0c6d)



Here is "surface_temp" field output from:
`/g/data/cj50/access-om2/raw-output/access-om2-025/025deg_jra55v13_ryf9091_gmredi6/output052/ocean/ocean_month.nc`
![2004-12_surface_temp_ACCESS-OM2-025_SH](https://github.com/dpath2o/AFIM/assets/1684347/548dbc0d-f633-4185-8c53-bc651ed2d9a7)


see http://131.217.175.138/~ec2-user/GRAPHICAL/initial_conditions/2004_12/ for the other fields from that NetCDF file

**Comment by dpath2o** [comment]
see http://131.217.175.138/~ec2-user/GRAPHICAL/initial_conditions/2004_12/ for the other fields from that NetCDF file

**Comment by ofa001** [comment]
Hi @dpath2o I was thinking overnight your daily data will not be as far apart as Noah's data but I would still prefer you to use the sst data from the restart file for your restart as the forcing data is being read into the model for a different purpose.  The restart file has expected the sst and frzmlt to be in the restart on the first timestep for stand alone model and it was missing as you used access-om2 restart file , subsequent restarts it will be included.

**Comment by dpath2o** [comment]
this issue can be closed as well

`[da1339@gadi-login-09 ~]$ ncks -m ~/gdata/afim_input/initial_conditions/0p25.iced.1993-01-01.with_o2i.nc
netcdf 0p25.iced.1993-01-01.with_o2i {
  dimensions:
    ncat = 5 ;
    ni = 1440 ;
    nj = 1080 ;

  variables:
    double Tsfcn(ncat,nj,ni) ;
      Tsfcn:_FillValue = NaN ;

    double aicen(ncat,nj,ni) ;
      aicen:_FillValue = NaN ;

    double frzmlt(nj,ni) ;
      frzmlt:_FillValue = NaN ;

    double iceumask(nj,ni) ;
      iceumask:_FillValue = NaN ;

    double qice001(ncat,nj,ni) ;
      qice001:_FillValue = NaN ;

    double qice002(ncat,nj,ni) ;
      qice002:_FillValue = NaN ;

    double qice003(ncat,nj,ni) ;
      qice003:_FillValue = NaN ;

    double qice004(ncat,nj,ni) ;
      qice004:_FillValue = NaN ;

    double qsno001(ncat,nj,ni) ;
      qsno001:_FillValue = NaN ;

    double scale_factor(nj,ni) ;
      scale_factor:_FillValue = NaN ;

    double sice001(ncat,nj,ni) ;
      sice001:_FillValue = NaN ;

    double sice002(ncat,nj,ni) ;
      sice002:_FillValue = NaN ;

    double sice003(ncat,nj,ni) ;
      sice003:_FillValue = NaN ;

    double sice004(ncat,nj,ni) ;
      sice004:_FillValue = NaN ;

    double ss_tltx(nj,ni) ;
      ss_tltx:_FillValue = NaN ;

    double ss_tlty(nj,ni) ;
      ss_tlty:_FillValue = NaN ;

    double sss(nj,ni) ;
      sss:_FillValue = NaN ;

    double sst(nj,ni) ;
      sst:_FillValue = NaN ;

    double stress12_1(nj,ni) ;
      stress12_1:_FillValue = NaN ;

    double stress12_2(nj,ni) ;
      stress12_2:_FillValue = NaN ;

    double stress12_3(nj,ni) ;
      stress12_3:_FillValue = NaN ;

    double stress12_4(nj,ni) ;
      stress12_4:_FillValue = NaN ;

    double stressm_1(nj,ni) ;
      stressm_1:_FillValue = NaN ;

    double stressm_2(nj,ni) ;
      stressm_2:_FillValue = NaN ;

    double stressm_3(nj,ni) ;
      stressm_3:_FillValue = NaN ;

    double stressm_4(nj,ni) ;
      stressm_4:_FillValue = NaN ;

    double stressp_1(nj,ni) ;
      stressp_1:_FillValue = NaN ;

    double stressp_2(nj,ni) ;
      stressp_2:_FillValue = NaN ;

    double stressp_3(nj,ni) ;
      stressp_3:_FillValue = NaN ;

    double stressp_4(nj,ni) ;
      stressp_4:_FillValue = NaN ;

    double strocnxT(nj,ni) ;
      strocnxT:_FillValue = NaN ;

    double strocnyT(nj,ni) ;
      strocnyT:_FillValue = NaN ;

    double swidf(nj,ni) ;
      swidf:_FillValue = NaN ;

    double swidr(nj,ni) ;
      swidr:_FillValue = NaN ;

    double swvdf(nj,ni) ;
      swvdf:_FillValue = NaN ;

    double swvdr(nj,ni) ;
      swvdr:_FillValue = NaN ;

    double uocn(nj,ni) ;
      uocn:_FillValue = NaN ;

    double uvel(nj,ni) ;
      uvel:_FillValue = NaN ;

    double vicen(ncat,nj,ni) ;
      vicen:_FillValue = NaN ;

    double vocn(nj,ni) ;
      vocn:_FillValue = NaN ;

    double vsnon(ncat,nj,ni) ;
      vsnon:_FillValue = NaN ;

    double vvel(nj,ni) ;
      vvel:_FillValue = NaN ;
} // group /`
